[tool.pyright]
venvPath = "."  # Or the relative path to your virtual environment directory
venv = ".env"
typeCheckingMode = "basic"  
reportMissingImports = true
reportUnusedVariables = true
reportGeneralTypeIssues = true
reportUnnecessaryComparison = true
reportUnnecessaryCast = true
reportUnnecessaryIsinstance = true
reportUntypedFunctionDefinition = false  # FastAPI often uses decorators on untyped functions
reportUntypedClassVariable = false
reportUntypedInstanceVariable = false
reportUntypedPublicAttribute = false
